[package]
authors = ["Maiori", "MarkosTh09"]
description = "Tool to convert Lua code into Clue code\nMade by MarkosTh09 and Maiori"
repository = "https://github.com/ClueLang/Probe"
edition = "2021"
name = "probe"
version = "0.1.1-beta"

[build-dependencies]
winres = "0.1"

[dependencies]
clap = {version = "4.0.8", features = ["derive"]}
