[package]
authors = ["Maiori", "MarkosTh09"]
description = "Tool to convert Lua code into Clue code\nMade by MarkosTh09 and Maiori\nhttps://github.com/ClueLang/Find\nhttps://github.com/ClueLang/Clue"
edition = "2018"
name = "find"
version = "0.9.0-indev"

[build-dependencies]
winres = "0.1"

[dependencies]
clap = {version = "3.1.6", features = ["derive"]}
