name: Test
on:
  push:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Cache build
        uses: Swatinem/rust-cache@v2
      - name: Setup
        run: |
          cargo install cargo-all-features
      - name: Check
        run: cargo check-all-features
      - name: Test
        run: cargo test-all-features
